# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Orus <3
email: luisboniche@ya.ru
description: >- # this means to ignore newlines until "baseurl:"
 Bienvenidos a nuestro sitio, un lugar donde podrás encontrar una 
 colección de poemas y películas vistas por nosotros, mi pareja y yo.
 En esta página podrás encontrar una selección de poemas que hemos escrito
 y compartido con el mundo, así como un archivo de películas que hemos visto y calificado. 
 Si estás buscando inspiración para tus propios poemas o simplemente quieres disfrutar de 
 la belleza de la palabra escrita, nuestro sitio es el lugar perfecto para ti. Además, si 
 eres un cinéfilo y quieres conocer nuestras recomendaciones de películas, también puedes 
 encontrar una lista de nuestras películas favoritas y nuestras calificaciones de ellas. 
 ¡Esperamos que disfrutes de tu visita a nuestro sitio y que encuentres algo que te inspira!
baseurl: "" # the subpath of your site, e.g. /blog
url: "cube-orus.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  Connor

theme: jekyll-whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/